apiVersion: v1
kind: Secret
metadata:
  name: kibana-kibana-es-token
  namespace: logging
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/instance: kibana
type: Opaque
stringData:
  token: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1raWJhbmE6WXVkXzlGZjlRUEd5MnMyOGg2ZjRQUQ"
